name: Build vtj.tar

on:
  push:
    branches: [main, master]
  workflow_dispatch:          # 手动触发也可

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. 设置 Buildx（支持缓存）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. 构建镜像（本地 docker 引擎，不推送）
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: vtj:latest
          outputs: type=docker,dest=vtj.tar   # 关键：
